/* automatically generated by rust-bindgen */

pub const LOCALE_SDECIMAL: u32 = 14;
pub const LOCALE_STHOUSAND: u32 = 15;
pub const LOCALE_SGROUPING: u32 = 16;
pub const LOCALE_SMONDECIMALSEP: u32 = 22;
pub const LOCALE_SMONTHOUSANDSEP: u32 = 23;
pub const LOCALE_SMONGROUPING: u32 = 24;
pub const LOCALE_SNEGATIVESIGN: u32 = 81;
pub const LOCALE_NAME_SYSTEM_DEFAULT: &'static [u8; 22usize] = b"!x-sys-default-locale\0";
